### ISSUE TITLE
The Appimage doesn't work on debian (buster)

### ISSUE THREAD

**Issue by bestlibre** [scheckmedia/photils-cli#3]
Hello,

I wanted to try your tool on debian, but I got the following error : 
```
photils-cli: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by photils-cli)
photils-cli: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_photiltxG9hA/usr/bin/../lib/libopencv_imgcodecs.so.4.3)
photils-cli: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_photiltxG9hA/usr/bin/../lib/libopencv_core.so.4.3)
```

**Comment by scheckmedia** [comment]
Which version of Debian are you using?

**Comment by bestlibre** [comment]
I'm using buster (the last stable to date)

**Comment by bestlibre** [comment]
The problem comes from the use of gcc-9 which is not available in debian stable. To build with gcc-8 I had to add `link_libraries(stdc++fs)` in the CmakeLists.txt. The resulting appimage is working on my system.

**Comment by scheckmedia** [comment]
Thanks for your help! I've downgraded GCC to version 8 and updated the build process. The new release with tag 0.21b should solve this issue. Can you check this (if the build is complete), when you have some minutes?

**Comment by bestlibre** [comment]
I don't see the AppImage in the release assets. I will test as soon as possible when the AppImage is ready.

**Comment by bestlibre** [comment]
It's working without problems. Thanks !
