### ISSUE TITLE
Whatever the processed image all 3690 tags are displayed

### ISSUE THREAD

**Issue by deuzene** [scheckmedia/photils-cli#5]
photils-cli-linux-x86_64.AppImage always find 3690 tags whatever the input image.

**Comment by scheckmedia** [comment]
Yes but they are sorted by accuracy. To see only N results you can pipe the output.

`photils-cli-linux-x86_64.AppImage ... |head -n 10` for the top ten tags.

**Comment by deuzene** [comment]
Ok, I didn't know about that. Thanks.

**Comment by scheckmedia** [comment]
No problem, there is also a flag to show the probability.

**Comment by deuzene** [comment]
> No problem, there is also a flag to show the probability.

What flag are you talking about? According to the README there are only -h -i and -o flags.

**Comment by scheckmedia** [comment]
--help shows you that -c is responsible to print out the confidence as well. I've forget to update the flag in the readme .

**Comment by deuzene** [comment]
Wow that's cool! Thanks for the job.
