### ISSUE TITLE
Release does not support label override

### ISSUE THREAD

**Issue by gnmackenzie** [scheckmedia/photils-cli#7]
Thank you very much for this utility.

The linux appimage release does not include the label override feature. I compiled a new appimage from the latest source and the feature worked.

Thanks again.

**Comment by mpaglia0** [comment]
Same problem here.
I am testing the Italian translation but labels override cannot work.
Started <darktable -d lua> and see following error messages:

7,402515 LUA use export to for prediction
[_dev_auto_apply_presets] missing mandatory module rawprepare for image 11201
[_dev_auto_apply_presets] missing mandatory module temperature for image 11201
[_dev_auto_apply_presets] missing mandatory module highlights for image 11201
[_dev_auto_apply_presets] missing mandatory module demosaic for image 11201
[_dev_auto_apply_presets] missing mandatory module colorin for image 11201
[_dev_auto_apply_presets] missing mandatory module colorout for image 11201
[_dev_auto_apply_presets] missing mandatory module gamma for image 11201

**Comment by scheckmedia** [comment]
Yes the last commit was not able to run on all CI stages and therefore the release was not published. I'll have a look to migrate everything to Githubs' actions to solve this issue. Alternatively, you can build everything from the source as @gnmackenzie mentioned.

**Comment by scheckmedia** [comment]
@mpaglia0 Seems I make some progress with the refactoring and GitHub actions. Can you check whether you can download the artifacts here: 
https://github.com/scheckmedia/photils-cli/suites/7197260554/artifacts/287704763

This will be a very early beta which also replaces some necessary dependencies.

**Comment by mpaglia0** [comment]
@scheckmedia works good!
Now I can see labels in Italian.
Moreover my terminal shows no messages with <darktable -d lua>
Thanks indeed!!
Maurizio

**Comment by scheckmedia** [comment]
Molto bene! 😄 I'll prepare the release as soon as possible. Thanks for testing.

**Comment by scheckmedia** [comment]
Fixed by #9

**Comment by gnmackenzie** [comment]
Thank you for your work it is most appreciated.
